### ISSUE TITLE
JOSS Review: Paper comments

### ISSUE THREAD

**Issue by emilydolson** [bramvandijk88/cacatoo#16]
Here are my comments on the paper submitted to JOSS (https://github.com/openjournals/joss-reviews/issues/3948).

This is a really cool project and I very much enjoyed reading the paper! Great work! The only remotely substantive changes I'd suggest are:

- Adding some discussion of how Cacatoo differs from Artistoo (i.e. under what circumstances would you want to use Cacatoo instead?).
- Adding some discussion of assumptions that Cacatoo makes/more precision about what the intended use case is. For example, the fact that there is only one grid that is constantly being updated (rather than a "current" grid and a "next" grid) means that if you aren't careful to have `nextState` only affect the focal cell, you can get artifacts based on the order the cells are updated in. You can usually get around this issue by using asynchronous updates, but I'm not positive that you always can, so it would probably be good to call it out explicitly in either the paper or the documentation.

# Minor typographical issues

- There is an extra set of parentheses around the second citation on line 33
- On line 35, parentheses are missing around "Figure 1".
- Line 74, there is a space between "d3." and "js" that I don't think is supposed to be there 
- Is there any way to add a citation for CASH? The link to the author's page could easily break in the future.

**Comment by bramvandijk88** [comment]
I have just made some minor text changes to cover these issues. I have clarified what Cacatoo brings to the table compared to Artistoo in the paper:

> Other than Artistoo, which first and foremost specialises on tissue simulations, Cacatoo provides easy-to-use functions for individual-based modeling (roulette wheel selection, random walks, neighbourhood retreival), reaction diffusion systems (ordinary differntial equations), and tools to build your own user interface (displays, graphs, sliders, interaction with mouse and keyboard, etc.).

... and fixed the minor typographical issues you mentioned.

Next, you are absolutely on-point about the fact that I do not go into detail on what it entails to work with a grid-based models (e.g. synchronous vs asynchronous updating, as you explain), but I feel like it would require quite a few words to really go into that topic (it also feels out of place in the paper). Instead, I have elaborated on this point in the introducing tutorial (https://bramvandijk88.github.io/cacatoo/first_project.html):

> Note that synchronous updating necessitates that one does **not** modify the neighbouring grid points in the nextState function, as this would mean a grid point that was already updated can be modified again by one of its neighbouring grid points. If you want to modify neighbouring grid points in the nextState function, always make sure to update the grid asynchronously (using _this.asynchronous()_ instead of _this.synchronous()_), which updates all grid points in a random order.

I have also added an FAQ that may cover this particular type of artifact. 

About the CASH-ciatation: there is, unfortunately, no official publication of CASH. The first version is from the 80s, and none of the updates since made it into an official methods paper.

**Comment by emilydolson** [comment]
These updates look good to me! I think the documentation is a fine place to discuss the synchronous/asynchronous point
